#!/bin/bash

################################################
# set default parameters

PATH=$(dirname $0):${PATH}

BASE_DIR=$(dirname $0)/..
SOURCE=${BASE_DIR}/mainichi
ANNOTATION=${BASE_DIR}/closed
DESTINATION=${BASE_DIR}/treebank


################################################
# collect command line given parameter values

while test $# -gt 0 ; do
  case "$1" in

      --diff)
         DIFF=1 ; shift 1 ;;

      --meld)
         MELD=1 ; DIFF=1 ; shift 1 ;;

      --data)
         DATA="${DATA} $2" ; shift 2 ;;

      --source)
         SOURCE="$2" ; shift 2 ;;

      --annotation)
         ANNOTATION="$2" ; shift 2 ;;

      --destination)
         DESTINATION="$2" ; shift 2 ;;

      *) echo "$1 is not an option."; exit ;;

  esac
done


################################################
# check there are directories

if test ! -d "${SOURCE}"; then
  echo "The script cannot complete."
  echo "There is no \"${SOURCE}\" directory."
  exit
fi

if test ! ${DIFF}; then
  if test ! -d "${ANNOTATION}"; then
    echo "The script cannot complete."
    echo "There is no \"${ANNOTATION}\" directory."
    exit
  fi
  if test ! -d "${DESTINATION}"; then
    echo "The script cannot complete."
    echo "There is no \"${DESTINATION}\" directory."
    exit
  fi
fi


################################################
# determine DATA

if test ! "${DATA}"; then
  DATA="950101 950103"
fi


################################################
# parts

function character_per_line () {
  awk -v NAME=$1 '{ n = split($0, parts, "") ; for (i = 1; i <= n; i++) { print parts[i], ++num, NAME } }'
}


################################################
# main script

for i in ${DATA}; do
  TEMP1="${TMP:-/tmp}/output_source_${i}"
  TEMP2="${TMP:-/tmp}/output_annotated_${i}"
  ##
  extract_data --extension ".org" --dir "${SOURCE}" --look "${i}" | \
  iconv -c -f EUC-JP -t UTF-8 | \
  grep -v "^#" | \
  character_per_line ${i} > ${TEMP1}
  ##
  if test ${DIFF}; then
    Keyaki "_${i}" | yield -j | character_per_line "${i}" > ${TEMP2}
    if test "${MELD}"; then
      meld ${TEMP1} ${TEMP2}
    else
      diff ${TEMP1} ${TEMP2}
    fi
  else
    echo "${i}"
    cat ${TEMP1} | awk '{ print $1 }' > ${TEMP2}
    extract_data --extension ".psd" --dir "${ANNOTATION}" --look "${i}" | \
    obfuscate_to_tree ${TEMP2} | \
    munge-trees -p | \
    sed "s/^(/\n(/" > "${DESTINATION}/$(extract_data --extension ".psd" --dir "${ANNOTATION}" | grep "${i}" | awk '{ print $2 }')".psd
  fi
  rm ${TEMP1} ${TEMP2}
done

